package main

import (
	"example.com/rest-api/db"
	"example.com/rest-api/routes"
	"github.com/gin-gonic/gin"

	"example.com/rest-api/docs" // docs is generated by Swag
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title ShopSmart API
// @version 1.0
// @description This is the ShopSmart API.

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
func main() {
	db.InitDB()
	db.CreateTables()

	server := gin.Default()
	docs.SwaggerInfo.BasePath = "/"
	routes.RegisterRoutes(server)
	server.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	server.Run(":8003")
}
